### ISSUE TITLE
Support Content-Security-Policy in production environments

### ISSUE THREAD

**Issue by aduth** [ViewComponent/lookbook#202]
This is a continuation of the discussion from https://github.com/allmarkedup/lookbook/issues/73#issuecomment-1095493655

Lookbook appears to be mostly compatible with applications which apply a CSP in local development, since it disables the CSP:

https://github.com/allmarkedup/lookbook/blob/1cd82025631762f40ed853ac8eb65574d4c28033/app/controllers/lookbook/application_controller.rb#L3-L5

However:

- This doesn't work in non-development environments
- This is perhaps more heavy-handed than it needs to be, since it would be good to retain a CSP as much as possible if one is configured

In some testing, I was able to find a policy configuration which respects an existing CSP, adding necessary directives for Lookbook:

```rb
module Lookbook
  class ApplicationController < ActionController::Base
    if respond_to?(:content_security_policy)
      before_action :remove_unsafe_eval_nonce_directives
      def remove_unsafe_eval_nonce_directives
        return if request.content_security_policy_nonce_directives.blank?
        request.content_security_policy_nonce_directives -= ['script-src']
      end

      content_security_policy do |policy|
        if policy.directives['script-src'].present?
          policy.script_src(*policy.script_src, :unsafe_inline, :unsafe_eval)
        end

        if policy.directives['style-src'].present?
          policy.style_src(*policy.style_src, :unsafe_inline)
        end
      end
    end

    # ...
  end
end
```

I was considering to open a pull request with this change, but in testing this, I found that while the implementation works for the top-level route, it doesn't extend to individual previews. It appears that this is because the individual previews are handled by a ViewComponent controller implementation, which [has a similar piece of code to disable the content security policy](https://github.com/ViewComponent/view_component/blob/22dbe8f648b44cc73d9663082a3e5024345b28ee/app/controllers/concerns/view_component/preview_actions.rb#L13).

To that end, I wonder if Lookbook ought to either...

- Disable the CSP consistently regardless of environment, for simplicity and consistency with ViewComponent
- Take an approach as in the code snippet above, for compatibility with an application's own CSP

Personally, I wouldn't be strongly opposed to disabling the CSP regardless of environment as being the simplest option, as long as it's constrained to the Lookbook-specific routes.

**Comment by aduth** [comment]
I think it could be fair (and simplest) to follow ViewComponent's lead here 👍 

As for downsides, I think the main thing is that if someone has gone through the effort of setting up a CSP, they'd presumably like to see it enforced consistently. On the other hand, it's common to need to poke holes in one's own CSP to allow additional exceptions, and it's mitigated slightly by limiting to the Lookbook-specific paths. In our case (and I'd expect/hope is common), we're not planning to make the component previews available in our user-facing production environments, but we do configure our lower staging environments as production-like.

**Comment by allmarkedup** [comment]
Hey @aduth - thanks for the reply and sorry it's taken so long to get back to you - had a busy few weeks.

I'll update the CSP code as discussed and get the change out in the next release. Many thanks for your help with this :-)

**Comment by aduth** [comment]
Hey @allmarkedup , sorry for the delayed response, but thanks (again) for picking this so quickly. I'll try to find some time to take it for a spin on our end and I'll let you know if we run into any issues.

Thanks!

**Comment by allmarkedup** [comment]
@aduth excellent! Thanks for giving it a test and really appreciate all your input on this one :-)
