### ISSUE TITLE
Param type `date` returns current date and time after it is cleared

### ISSUE THREAD

**Issue by mdrbohlav** [ViewComponent/lookbook#219]
### Describe the bug

When I set param of type `date` and then clear it it always returns the current date and time even though it should be empty. The URL param is empty but the param in the preview method is not.

### To Reproduce

Create a preview with param type `date`.
Open the preview in the lookbook and select a date.
Clear the value using the button in the HTML5 input UI.
The URL param is empty but in the preview method it is set.

### Expected behavior

The preview method param should be empty.

### Version numbers 

Please complete the following information:

* Lookbook: 1.2.1
* ViewComponent: 2.74.1
* Rails: 7.0.4
* Ruby: 3.1.2

**Comment by allmarkedup** [comment]
@mdrbohlav thanks for this - I'll take a look at this and hopefully get a fix out in the next release 👍

**Comment by allmarkedup** [comment]
Hey @mdrbohlav this should be fixed in the latest release (v1.3.2). Can you give it a test and let me know if works as expected now?

**Comment by mdrbohlav** [comment]
Looks great! Thank you for the quick fix!
