### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by camertron** [ViewComponent/lookbook#224]
Hey there @allmarkedup! Is the release process documented anywhere, and is there a changelog? We use changesets in primer/css and primer/view_components to automate releasing changes, updating the changelog, etc. Might be useful here too?

**Comment by allmarkedup** [comment]
Hey @camertron - unfortunately I do not have anything documented around the release process yet. It's on my (long) list of todos though, as well as giving other ViewComponent members RubyGems publish access.

I currently use [release-it](https://github.com/release-it/release-it) to handle all aspects of the release, but (currently) there is no standalone changelog, just the release notes that accompany the Github releases. But that is also something I'd definitely like to change/improve. I've not looked at changesets before but I'll certainly check it out, thank you.

There are a few other things I need to sort out with the release process - probably the main one is that currently the documentation site gets updated every time code is pushed to master. Which can mean that the documentation gets updated before the new version is actually released which is not ideal! So I need to change to triggering a doc site update as part of the release process instead - something I'll get to as soon as I have a bit more time.

Tbh I normally try get new releases out pretty regularly but I've had some family stuff to deal with recently that has put me a bit behind with everything. But I'm catching up now and will look at putting a little more structure/documentation around the release process in the next week or so if I can, as I realise it's not really optimal right now.

As an aside, I'm also hoping to get a new release out this weekend with the `logical_path` changes (and a whole bunch of refactoring work).

Thanks for bringing this up - it's a good reminder that I need to sort these things out :-)

**Comment by camertron** [comment]
> I currently use [release-it](https://github.com/release-it/release-it) to handle all aspects of the release

Oh cool, automation is the best 👍 

> but (currently) there is no standalone changelog, just the release notes that accompany the Github releases.

Is that something release-it can manage for you? It's always nice to be able to quickly scan a changelog.

> There are a few other things I need to sort out with the release process - probably the main one is that currently the documentation site gets updated every time code is pushed to master. Which can mean that the documentation gets updated before the new version is actually released

Haha yeah, if I recall correctly view_component and primer/view_components suffer from that problem as well 😅 

> Tbh I normally try get new releases out pretty regularly but I've had some family stuff to deal with recently that has put me a bit behind with everything. But I'm catching up now and will look at putting a little more structure/documentation around the release process in the next week or so if I can, as I realise it's not really optimal right now.

Absolutely no pressure, I was just wanting to pull the logical path stuff into our view_components Lookbook. Looks like a new version got published yesterday though 🎉 Thank you!

**Comment by allmarkedup** [comment]
thanks @camertron but I'll leave it open as a reminder until I've actually done some documentation done :-)
