### ISSUE TITLE
Does this really require the exact versions for rouge 3.26+, zeitwerk 2.5.0+, yard 0.9.24+, htmlentities 4.3.4+?

### ISSUE THREAD

**Issue by SleeplessByte** [ViewComponent/lookbook#287]
Our production ecosystem is based on debian and not on rubygems. Our development systems are basically a VM of the production environment (think docker, but then just a stable debian install). This means that we cannot install gems from RubyGems on production, and _shouldn't_ install gems on development, with the upside being that any gem we install via debian gets automatic security updates, and that our development environments _exactly match_ the production environment.

<details>
<summary>For example</summary>

```shell
$ apt-get install ruby-css-parser

[...]

The following NEW packages will be installed:
  ruby-css-parser
0 upgraded, 1 newly installed, 0 to remove and 40 not upgraded.

[...]

Setting up ruby-css-parser (1.6.0-1) ...
```

This installs the package in a system location and can now be found when using `gem 'css-parser'`

```shell
$ dpkg -L ruby-css-parser

/.
/usr
/usr/lib
/usr/lib/ruby
/usr/lib/ruby/vendor_ruby
/usr/lib/ruby/vendor_ruby/css_parser
/usr/lib/ruby/vendor_ruby/css_parser/parser.rb
/usr/lib/ruby/vendor_ruby/css_parser/regexps.rb
/usr/lib/ruby/vendor_ruby/css_parser/rule_set.rb
/usr/lib/ruby/vendor_ruby/css_parser/version.rb
/usr/lib/ruby/vendor_ruby/css_parser.rb
/usr/share
/usr/share/doc
/usr/share/doc/ruby-css-parser
/usr/share/doc/ruby-css-parser/README.md
/usr/share/doc/ruby-css-parser/changelog.Debian.gz
/usr/share/doc/ruby-css-parser/changelog.gz
/usr/share/doc/ruby-css-parser/copyright
/usr/share/rubygems-integration
/usr/share/rubygems-integration/all
/usr/share/rubygems-integration/all/specifications
/usr/share/rubygems-integration/all/specifications/css_parser-1.6.0.gemspec
```
</details>

There are many gems maintained by the debian ruby team, but of course a gazillion more that are not in debian. For example, `view_component (2.55.0)` [doesn't exist on stable](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=ruby-view-component), but will be added in the next version (~1.8 years from now). For these gems, if the dependencies allow for it, they can be added in the vendor folder.

```ruby
gem 'view_component', path: File.join(__dir__, 'vendor', 'view_component-2.55.0')
```

This works because the two runtime dependencies `view_component` has exist on debian!

- `activesupport (>= 5.0.0, < 8.0)` as [`ruby-activesupport (6.0.3.7)`](https://packages.debian.org/bullseye/ruby-activesupport) 
- `method_source (~> 1.0)` as [`ruby-method-source (1.0.0)`](https://packages.debian.org/bullseye/ruby-method-source) 

This means that installing those packages first, followed by vendoring the gem can make a working `Gemfile.lock` using `bundle install --local`. Swell!

-----------

`lookbook` lists the following:

- `required_ruby_version >= 2.7.0` matching [`ruby (2.7)`](https://packages.debian.org/bullseye/ruby)
- `css_parser` matching [`ruby-css-parser (6.0)`](https://packages.debian.org/bullseye/ruby-css-parser)
- `actioncable` matching [`ruby-actioncable (6.0.3.7)`](https://packages.debian.org/bullseye/ruby-actioncable)
- `activemodel` matching [`ruby-activemodel (6.0.3.7)`](https://packages.debian.org/bullseye/ruby-activemodel)
- `zeitwerk ~> 2.5.0` **NOT matching** [`ruby-zeitwerk (2.4.2)`](https://packages.debian.org/bullseye/ruby-zeitwerk)
- `railties ~> 5` matching [`ruby-railties (6.0.3.7)`](https://packages.debian.org/bullseye/ruby-railties)
- `view_component ~> 2.0` missing
- `redcarpet ~> 3.5` matching [`ruby-redcarpet (3.5.1)`](https://packages.debian.org/bullseye/ruby-redcarpet)
- `rouge >= 3.26, < 5.0` **NOT matching** [`ruby-rouge (3.21.0)`](https://packages.debian.org/bullseye/ruby-rouge)
- `listen ~> 3.0` matching [`ruby-listen (3.2.1)`](https://packages.debian.org/bullseye/ruby-listen)
- `yard ~> 0.9.25` **NOT matching** [`yard (0.9.24)`](https://packages.debian.org/bullseye/yard)
- `htmlbeautifier ~> 1.3` missing
- `htmlentities ~> 4.3.4` **NOT matching** [`ruby-htmlentities (4.3.3)`](https://packages.debian.org/bullseye/ruby-htmlentities)

Most of these versions were added in this commit: https://github.com/ViewComponent/lookbook/commit/77d14397cc9fe63e191a0930629c3c344aafd7a9, which seems to "just add" versions as they appeared in the lock, and not be the actual dependent versions.

### Describe the solution you'd like

I'd like to know if the version added were added with a reason other than having versions in there or not. If there is an actual feature that was added in `rouge` after 3.21 that is missing in 3.21, or zeitwerk` 2.5.0, that is missing in 2.4.2, we won't be able to use lookbook, but in every other case:

`yard` has had a security update, so the security patch from 0.9.25 made it to the 0.9.24 version in debian. The same is true for `htmlentities`. The missing gems `htmlbeautifier` and `view_component` can be vendored because either they don't have dependencies, or all dependencies are matching in debian or can be vendored themselves.

### Describe alternatives you've considered

Going down the rabbit hole myself before asking.

### Additional context

If you confirm that these versions were just added because it's the versions you know of, I will go through the motion of testing `lookbook` with the lower versions (with the debian packages). You don't need to lower the gemspec versions or anything, although be aware that the _gemspec_ versions should be the minimum version _required_, or at least that's how I understood gem development to be, and how I deal with it in my own gems.

**Comment by allmarkedup** [comment]
Hey @SleeplessByte thanks for opening this issue - I'm always amazed at how different everyone's setups are but I'd love to help get this working for you.

In answer to your question, there is no particular reason (that I can remember!) that the gem dependencies need to be tied to those specific versions. Unfortunately my commit message on that commit is spectacularly unhelpful in helping remember but I think at the time I was just trying to ensure I had a know, workable set of dependency versions to build on. Lookbook was somewhat in it's infancy then :-)

I'm pretty sure they could be lowered to meet your requirements without any side effects. Would you be interested in opening a PR to lower the versions to better match your requirements to unlock this for you? I'd be happy to then double check everything to make sure it's not causing any issues.

Then when I have a bit of time I can see if I can drop those version still lower to help others that might be in similar situations.

Let me know what you think :-)

**Comment by SleeplessByte** [comment]
Oh sweet. 

Yeah, I'll setup a fork with the lowered versions so they would be good to go with our setup. FWIW I won't _need_ you to lower the versions in the repo as well, as this isn't packaged yet so I'd just do that before packaging or vendoring -- but of course you could!

**Comment by allmarkedup** [comment]
Okay great, nice one - there would be no harm in lowering the versions once they are confirmed to work, so if you get your branch running ok then I might as well match the spec in here I think :-)

Let me know if I can do anything else to help!

**Comment by allmarkedup** [comment]
@SleeplessByte I'm going to close down this issue now, if you end up putting together a PR we can always continue any discussion in there - or feel free to reopen if needed!

**Comment by SleeplessByte** [comment]
Yep, thanks! 

Currently running a few live events, but will pick this up after. See you in the future!

**Comment by SleeplessByte** [comment]
Fast forward to 2024. I got extremely ill and hospitalised for almost a year, so I wasn't able to pick this up but "luckily" I no longer need to. 

Here to report that this made it into current [stable @ 2.74](https://packages.debian.org/bookworm/ruby-view-component), and the current version @ [3.12 is in the next version of debian (testing)](https://packages.debian.org/trixie/ruby-view-component). 

No further work needs to be done from your end.

**Comment by SleeplessByte** [comment]
Fast forward to 2024. I got extremely ill and hospitalised for almost a year, so I wasn't able to pick this up but "luckily" some things have happened.

Here to report that this made it into current [stable @ 2.74](https://packages.debian.org/bookworm/ruby-view-component), and the current version @ [3.12 is in the next version of debian (testing)](https://packages.debian.org/trixie/ruby-view-component). 

No further work needs to be done to get view components into Debian.
As for lookbook, the dependencies have changed over time. I'll see if this now runs, and if not I'll let you know which things to (potentially) change.

**Comment by SleeplessByte** [comment]
I got `lookbook` 2.3.2 working on debian stable (bookworm) by making the following changes:

```diff
- spec.add_dependency "htmlentities", "~> 4.3.4"
+ spec.add_dependency "htmlentities", "~> 4.3.3"
```

In order to use system packages only, I needed to then:

```ruby
group :development do
  gem 'htmlbeautifier', path: File.join(__dir__, 'vendor', 'htmlbeautifier-1.4.3')
  gem 'htmlentities', '4.3.3'
  gem 'lookbook', path: File.join(__dir__, 'vendor', 'lookbook-2.3.2')
end
```

Finally, vendor that version of `htmlbeautifier` in the vendor folder and install `htmlentities`:

```shell
apt-get install ruby-htmlentities
```

All the other dependencies are already installed by other gems such as rails. Now `bundle install --local` succeeds.

Leaving this here for a future reader. As for this project, you may want to consider to downgrade the gemspec for `htmlentities` to `~> 4.3.3`, as the next version of debian currently still includes that non-latest version.
