### ISSUE TITLE
@label have low-contrast text which effects those with visual impairment. 

### ISSUE THREAD

**Issue by cody-clio** [ViewComponent/lookbook#307]
### Describe the bug
When using lookbook, I often found the additional text like @label or text used in params challenging to read. According to axe/lighthouse tooling, it's currently at low contrast and fails WCAG standards. 

### To Reproduce
Create any simple component and use the @label to increase the text on the page. 

### Expected behavior

Increase the contrast to a readable and a11y expected standard. 

### Screenshots

![Screenshot 2023-01-30 at 3 25 46 PM](https://user-images.githubusercontent.com/120416026/215619815-3d4f476c-e739-425c-8f3b-cdda3160345f.png)

### Version numbers 

Please complete the following information:

* Lookbook: 1.1.1
* ViewComponent: 2.55
* Rails: 6.0.4.1
* Ruby: 2.6.6

**Comment by allmarkedup** [comment]
Hey @cody-clio thanks for bringing this to my attention! Lookbook still needs quite a lot of improvement on the accessibility front I'm afraid 😕

Little improvements like your suggestion above are a good start though so I'll get that fixed and included in the next release. Thanks!

**Comment by allmarkedup** [comment]
Thanks @Spone - bookmarked :-)

**Comment by allmarkedup** [comment]
@cody-clio I've just pushed up a change to fix the contrast of the labels you mention and will include it in the next release.

I'm aware there are still other contrast issues within the app but I think I'm going to open a dedicated issue to track accessibility improvements that need to be made. So I'll close this down now but please feel free to chime in on that if you have any more specific suggestions. Thanks again :-)
