### ISSUE TITLE
Title in not centered vertically

### ISSUE THREAD

**Issue by Spone** [ViewComponent/lookbook#316]
### Describe the bug

The "Lookbook Demo" title is not centered vertically.

### To Reproduce

1. Visit https://v2-demo.lookbook.build/lookbook/pages/overview
2. See error

### Expected behavior

The text should be centered vertically.

### Screenshots

![image](https://user-images.githubusercontent.com/38524/216996539-767d6003-1748-47a5-b419-8c8257fcf49e.png)

It was already the case in v1, but less so.

![image](https://user-images.githubusercontent.com/38524/216996611-e53cf4c8-7ada-4173-b4e0-4c96ddc93bf8.png)

### Additional context

I'm using Firefox on Linux, but I see the same issue in Chromium.

**Comment by allmarkedup** [comment]
Thanks @Spone  - I'll look into it and get a fix out 👍
