### ISSUE TITLE
`url_for` not finding routes

### ISSUE THREAD

**Issue by joelmoss** [ViewComponent/lookbook#328]
### Describe the bug

`url_for` raises `ActionView::Template::Error` with `Undefined method `root_path' for #<ActionView::Base:XXX>`

### To Reproduce

```ruby
class Header::Component < Phlex::HTML
  def template
    div { helpers.url_for(:root) }
  end
end
```

### Expected behavior

The URL defined in the routes should be rendered.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta1
* Rails: 7.0.4.2
* Phlex: 1.3.2
* Phlex-rails: 0.6.1
* Ruby: 3.2.0

### Additional context

It looks like the application's routes are simply not loaded.

**Comment by allmarkedup** [comment]
Thanks for this @joelmoss - I'll try and dig into this and see what is happening here as soon as I have a chance. I assume the `url_for` helper is working correctly when using that component in a view in your app?

**Comment by joelmoss** [comment]
Yes it is working fine outside of lookbook.

FYI: Phlex exposes all Rails helpers and view context in the `helpers` proxy.

**Comment by allmarkedup** [comment]
@joelmoss I've just released [v2.0.0.beta.2](https://github.com/ViewComponent/lookbook/releases/tag/v2.0.0-beta.2) which should fix this issue.

I'll close this down now but if you are still having any issues with it after updating feel free to reopen. Thanks again for bringing it to my attention :-)

**Comment by joelmoss** [comment]
Perfect! 👌 thank you

**Comment by inkstak** [comment]
It doesn't seems to work when we try to add the params to the current path depending on Lookbook Engine.

In the example below, we use `url_for` to add the `order=title` to the current path whatever it is.

```ruby
class MyComponent < ViewComponent::Base
  def order_url
    helpers.url_for(order: "title")
  end
end
```

It raises an `ActionView::Template::Error`:

```
No route matches {:action=>"show", :controller=>"lookbook/inspector", :order=>:title, :path=>"my_component/default"}
```

**Comment by inkstak** [comment]
Here is my current workaround:

```ruby
class MyComponent < ViewComponent::Base
  def order_url
    if params[:controller]&.start_with?("lookbook")
      helpers.lookbook.url_for(order: current_order)
    else
      helpers.url_for(order: current_order)
    end
  end
end
```

**Comment by bjufre** [comment]
@allmarkedup This is happening with v2 as well. I'm trying to abstract a component with some request information that we need (it's a pagination component) and the `url_for` is failing. We need the code to look something like: 
```ruby
  def page_path(page)
    url_for(**@request_params, page: page)
  end
```

We had to do it like this because we're going to need the query params present in the page because we have a lot of pages with tables that have filtering and whatnot.

**Comment by allmarkedup** [comment]
@bjufre okay, thanks for letting me know - are you seeing the same `ActionView::Template::Error` as described in the original issue description above?

I haven't quite got a handle on why this is working for some folks but not others just yet but I'll take another look at it.

One thing to try in the meantime (if you are not already doing so) - can you set up a custom preview controller and configure ViewComponent to use that (I assume you are using ViewComponent?): https://viewcomponent.org/guide/previews.html#configuring-preview-controller - I've had reports that this fixes the issue for some folks so would be good to know if that helps at all for you.

**Comment by bjufre** [comment]
@allmarkedup we are using a custom PreviewController from our codebase 🤔 I will check to make sure that I'm not leaving anything behind but I don't think so. And for the error type that's exactly right too `ActionView::Template::Error` is what we're getting.

**Comment by bjufre** [comment]
@allmarkedup all of a sudden it started working... 
Now what I would like to do is to make it dynamic within Lookbook. How can I do that? I need to make sure that if someone is clicking one of the pagination links, we redirect them to the same Lookbook preview with the new `?page=5` querystring. Is that possible?
