### ISSUE TITLE
Defined preview_layout nil in test env

### ISSUE THREAD

**Issue by joelmoss** [ViewComponent/lookbook#332]
### Describe the bug

I have set `preview_layout` config, and it works fine during normal usage. But when I call a preview from a system test with capybara and cuprite, the `preview_layout` is nil.

### To Reproduce

```ruby
class CalendarsTest < ApplicationSystemTestCase
  test 'visiting the calendar' do
    visit '/lookbook/preview/calendar/default'
    assert_equal 'component_preview', Lookbook.config.preview_layout
  end
end
```

```
Failure:
CalendarsTest#test_visiting_the_calendar:
Expected: "component_preview"
  Actual: nil
```

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta2
* Rails: 7.0.4.2
* Ruby: 3.2.1

**Comment by joelmoss** [comment]
I think https://github.com/ViewComponent/lookbook/blob/v2/lib/lookbook/engine.rb#L34 is the culprit.

**Comment by allmarkedup** [comment]
@joelmoss hmm that is an odd one - is this in the same (Phlex) app as before? Are you actually using ViewComponent directly in your app? 

I'll look into this shortly. I have to do some pretty ugly checking to try and determine if ViewComponent is being used/included in the parent app as opposed to just by Lookbook itself, and set some config accordingly. If your app isn't using VC then it may be that my checks are too fragile and failing somewhere and that is causing the issue. If that is the case I'll have to try and see if there is a better way to handle it.

**Comment by allmarkedup** [comment]
@joelmoss I think I've found the issue - I've pushed a fix up now to the `v2` branch and I'll get it out in the next release. If you want to test it out in the meantime then you can use the v2 branch temporarily in your Gemfile:

```rb
gem 'lookbook', git: 'https://github.com/ViewComponent/lookbook', branch: 'v2'
```

If you could let me know how you get on whenever you get a chance to try it out that would be great 🙂

**Comment by joelmoss** [comment]
Works like a charm ✨ thx :+1:

**Comment by allmarkedup** [comment]
Great, will close this now then, thanks for letting me know 👍
