### ISSUE TITLE
all_view_paths undefined for ActionView::ViewPaths:Module

### ISSUE THREAD

**Issue by charlesobrien** [ViewComponent/lookbook#334]
### Describe the bug

Rails (edge) won't start.

`/usr/local/rvm/gems/default/gems/lookbook-2.0.0.beta.1/lib/lookbook/engine.rb:128:in `view_paths': undefined method `all_view_paths' for ActionView::ViewPaths:Module (NoMethodError)
ActionView::ViewPaths.all_view_paths.flat_map do |view_path|
from /usr/local/rvm/gems/default/gems/lookbook-2.0.0.beta.1/lib/lookbook/engine.rb:153:in `preview_watch_paths'`

### To Reproduce

Run a Rails app using bin/rails server or bin/dev.

### Expected behavior

Rails application should start.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0 Beta 2
* ViewComponent: 2.82.0
* Rails: 7.1.0 alpha (main@9192027)
* Ruby: 3.2.0

### Additional context

Appears to be related to https://github.com/rails/rails/commit/28284fc186800ab13a9ee1b141fc32d065f85528

**Comment by allmarkedup** [comment]
Thanks for this @charlesobrien - I'll look into it and get it fixed up. I also really need to ensure the tests are running against Rails edge too.

Appreciate you taking time to report the issue and help point me in the right direction, I'll let you know when it's fixed 👍

**Comment by allmarkedup** [comment]
@charlesobrien I've just pushed a fix up for this and will get a new release out soon - thanks for bringing it to my attention!

For some reason I'm struggling to add Rails edge added to the test matrix but once I've figured that out it should hopefully guard against things like this in the future. I've tested this fix manually however and it should do the jpb.

Let me know how you get whenever manage to give it a try.

**Comment by Spone** [comment]
@allmarkedup what's the issue with testing against rails edge? I think we got it figured out on VC 's repo.

**Comment by charlesobrien** [comment]
> @charlesobrien I've just pushed a fix up for this and will get a new release out soon - thanks for bringing it to my attention!
> 
> For some reason I'm struggling to add Rails edge added to the test matrix but once I've figured that out it should hopefully guard against things like this in the future. I've tested this fix manually however and it should do the jpb.
> 
> Let me know how you get whenever manage to give it a try.

Thanks, you're awesome! I'll pull main this weekend and give it a try.

**Comment by allmarkedup** [comment]
@charlesobrien great! Hopefully it's all fixed up :-)

**Comment by allmarkedup** [comment]
@Spone I'm not sure! Running `appraisal install` to generate the Gemfile always fails with a message about being unable to find `actionpack` 7.1 alpha. The VC repo works just fine for me so I'm not quite sure what is happening. Just trying to pick it apart now and see what might be different in the way I've got things set up in Lookbook.

**Comment by charlesobrien** [comment]
> @charlesobrien great! Hopefully it's all fixed up :-)

Just pulled v2 branch. App starts and appears things are back in order. Will test a bit more later. Thank you!

**Comment by allmarkedup** [comment]
@charlesobrien fantastic - I'll close this issue down now then, thanks for letting me know :-)

**Comment by Spone** [comment]
> @Spone I'm not sure! Running `appraisal install` to generate the Gemfile always fails with a message about being unable to find `actionpack` 7.1 alpha. The VC repo works just fine for me so I'm not quite sure what is happening. Just trying to pick it apart now and see what might be different in the way I've got things set up in Lookbook.

Here's the PR where everything's working (and tests are run through Appraisal in CI), if it can be of some help!
https://github.com/ViewComponent/view_component/pull/1308

**Comment by allmarkedup** [comment]
Thanks @Spone - will take a look at that now

**Comment by allmarkedup** [comment]
@charlesobrien I've just realised that the previous fix masked the problem but didn't actually fix it correctly, so I've just pushed a new change that should properly fix it this time

Related: @spone - I've got it working now! 🎉 😆 Thanks.
