### ISSUE TITLE
Beta hangs on websocket connection

### ISSUE THREAD

**Issue by allmarkedup** [ViewComponent/lookbook#337]
Having some trouble with the beta and not really sure how to debug. It was working for a bit and then I restarted my Rails server and now loading the `/lookbook` root page hangs in Chrome. Looks like it is waiting for actioncable to connect but never does? 
![image](https://user-images.githubusercontent.com/56947/219142529-f7b0d491-8663-4451-b9f1-75bff49e1dd0.png)

Eventually the tab freezes and has to be killed because it's taking 100% CPU.

We don't use actioncable (though it is installed via rails) so there might be something on my end that is not setup correctly?

_Originally posted by @swanson in https://github.com/ViewComponent/lookbook/discussions/310#discussioncomment-4987582_

**Comment by swanson** [comment]
Rails 7.0.4.2
Ruby 3.1.2
ViewComponent 2.82.0

**Comment by allmarkedup** [comment]
Thanks @swanson - I've not been able to recreate this yet but I'll try again when I have a chance and let you know when I've figured it out.

**Comment by allmarkedup** [comment]
Hi again @swanson. I'm afraid I've not had much more luck on this yet - I can't for the life of me recreate the issue.

As a partial workaround that may help with debugging, I've added a new `live_updates` config option that allows manual disabling of live UI updates in development even if the actioncable is present.

If you have a second at all it would be great if you could try disabling websockets by setting that option to `false` and seeing if Lookbook then functions normally for you (apart from having to refresh the pages to see any changes).

Docs are here: https://v2.lookbook.build/guide/config_reference#live_updates but the change hasn't yet made it's way into a new beta release yet, so you'd have to fetch the Lookbook gem from the `v2` branch for now:

```rb
gem "lookbook", git: "git://github.com/ViewComponent/lookbook.git", branch: "v2"
```

I should get another beta release out within a few days that will include this in it however so it may be easier to wait for that.

Thanks!

**Comment by swanson** [comment]
> Hi again @swanson. I'm afraid I've not had much more luck on this yet - I can't for the life of me recreate the issue.
> 
> As a partial workaround that may help with debugging, I've added a new `live_updates` config option that allows manual disabling of live UI updates in development even if the actioncable is present.
> 
> If you have a second at all it would be great if you could try disabling websockets by setting that option to `false` and seeing if Lookbook then functions normally for you (apart from having to refresh the pages to see any changes).
> 
> Docs are here: https://v2.lookbook.build/guide/config_reference#live_updates but the change hasn't yet made it's way into a new beta release yet, so you'd have to fetch the Lookbook gem from the `v2` branch for now:
> 
> ```ruby
> gem "lookbook", git: "git://github.com/ViewComponent/lookbook.git", branch: "v2"
> ```
> 
> I should get another beta release out within a few days that will include this in it however so it may be easier to wait for that.
> 
> Thanks!

That changes does seem to avoid the actioncable hang up (and would work for me, I dont particularly need live reload as long as changes to previews/components get picked up when I reload the page).

Now I did notice that lookbook was hanging / slow and got a bucket load of JS console errors (Maximum call stack size exceeded) and there is a noticeable lag when filtering in the left-hand sidebar
![image](https://user-images.githubusercontent.com/56947/220813769-db6291c2-a50d-4f72-8cbc-c5aa6523706b.png)

**Comment by allmarkedup** [comment]
@swanson hmm yeah there is something odd happening here. A couple of things to check -  can you make sure the browser cache is cleared for this domain so that you are definitely getting the latest JS (you have probably done this already), and can you also clear local storage? There is a link in the debug menu at the top right if needed.

It may be that some settings have been saved in localstorage that are no conflicting with the updated UI, so clearing it out may help. But I'm just clutching at straws here really until I'm able to see replicate so similar behaviour at my end.

Sorry you can't kick the tyres on the beta yet because of this - I'd love to hear any other feedback you might have on it when this issue gets resolved :-)

**Comment by allmarkedup** [comment]
@swanson sorry to ping you on this as I'm sure you are busy enough but I was wondering if you'd had a chance to see if clearing local storage had made any difference at all? 

I've not been able to replicate this at all and haven't heard any other reports of anything similar so it's I'm not really sure with how else to proceed on trying to figure out what is going on here I'm afraid 😕

**Comment by swanson** [comment]
@allmarkedup Hey sorry, I have not had time to debug further. Please feel free to close if no one else is experiencing the issues!

**Comment by allmarkedup** [comment]
@swanson no worries at all! Appreciate you getting back to me. I'll close this down for now then as it does (currently) seem to be an isolated issue but if you get a chance to come back to it and are still having troubles just reopen or let me know and I'l try to pick it up again. Many thanks :-)
