### ISSUE TITLE
Lookbook v2 website: 404 on live_reload

### ISSUE THREAD

**Issue by Spone** [ViewComponent/lookbook#341]
### Describe the bug

When visiting https://v2.lookbook.build, I see a lot of "live reload" XHR requests in the console, that return a 404 error.

### To Reproduce

1. Visit https://v2.lookbook.build
2. Open your browser's console
3. See errors

### Expected behavior

I would expect the live reload feature to be disabled in production.

### Screenshots

![image](https://user-images.githubusercontent.com/38524/220189789-12623d28-11e3-43f3-a5c5-ccf79d218e0b.png)

**Comment by allmarkedup** [comment]
Thanks @Spone - I hadn't set the BRIDGETOWN_ENV variable correctly when deploying. Fixed now!
