### ISSUE TITLE
When mounting Lookbook in another Rails Engine, asset paths and layouts don't always work

### ISSUE THREAD

**Issue by ksweetie** [ViewComponent/lookbook#359]
### Describe the bug

First off, just wanted to say that this project is amazing! Really glad I found it before committing to another Storybook project.

I'm creating a component library as a mountable Rails engine, so that it's completely isolated, and that engine mounts Lookbook:

```
Main app
  \
  Component Library (mounted)
    \
    Lookbook (mounted)
```

This makes the component library isolated and portable, so any project that wants to use it can also optionally mount a Lookbook app.

I've run into a couple of issues related to asset paths, where Lookbook is only checking the main app's `app/*` instead of `my_engine/app/*`:

1. **Preview paths** — This was easy to fix, because lookbook provides `config.lookbook.preview_paths`, so I'm able to pass it the full path like this: `config.lookbook.preview_paths = [MyEngine::Engine.root.join("app/components").to_s]`. Maybe a little unintuitive, but that works just fine.
2. **Layouts** — When specifying a layout, either individually or via `config.lookbook.preview_layout`, I'm seeing this:

```
ActionView::MissingTemplate
```

The error is helpful in that it shows which directories it searched in. It's showing my main app's `app/views` as well as `lookbook-2.0.0.beta.4/app/views`, but not my engine's `app/views`, where I want the preview layout to live.

### To Reproduce

I don't have an easy repro, but if my explanation doesn't make sense I can make one.

### Expected behavior

Lookbook should look for assets in the context it was mounted in, not necessarily (or in addition to) the root application. If this isn't possible automatically, maybe we could add a config option to point to the right directory.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta.4
* ViewComponent: 2.82.0
* Rails: 6.1.7.1
* Ruby: 3.2.1

### Additional context

I monkey patched `Lookbook::PreviewActions` as a temp fix. Here's what I did:

```rb
# lib/preview_actions.rb
module PreviewActions
  def render_in_layout_to_string(template, locals, opts = {})
    append_view_path MyEngine::Engine.root.join("app/views") # <~ This is what I needed to change

    with_optional_action_view_annotations do
      html = render_to_string(template, locals: locals, **determine_layout(opts[:layout]))
      if opts[:append_html].present?
        html += opts[:append_html]
      end
      render html: html
    end
  end
end

# lib/my_engine.rb
require "preview_actions"

# lib/my_engine/engine.rb
config.after_initialize do
  config.view_component.preview_controller.constantize.class_eval { prepend PreviewActions }
end
```

Not pretty, but it does fix the issue. Maybe there should be a new config option, like `config.lookbook.layout_paths`? Also possible that I'm missing something obvious and just going about this all wrong 😄 . Thanks in advance!

**Comment by allmarkedup** [comment]
Hey @ksweetie thanks for this! It may not be possible to figure out the preview paths automatically (the `preview_paths` config option is for exactly this use case as you have correctly figured out) but once that path is supplied I'm sure that I can get the layouts working without further configuration.

I'll take a look at it when I have a chance and let you know when I've got a fix.

Thanks for bringing to my attention and I'm glad you've been enjoying using it so far :-)

**Comment by allmarkedup** [comment]
@ksweetie okay so this is proving to be a little trickier than I thought to find a good generic solution to 🙂

Adding another config option for specifying view paths is definitely a possibility, but I'd rather not if I can avoid it as it's another thing to document and test - and this is a bit of an niche use case (although I very much like the idea!).

A cleaner way to work around the layout issue would probably be to specify a custom preview controller:

```rb
config.lookbook.preview_controller = "MyPreviewController"
```

And then in the preview controller prepend your engine's views directory:

```rb
class MyPreviewController < Lookbook::PreviewController
  prepend_view_path MyEngine::Engine.root.join("app/views")
end
```

Can you give that a try and see if it allows you to remove the monkey patch? If so I will probably add this as an example to the documentation rather than adding another config option.

Let me know how you get on!

**Comment by ksweetie** [comment]
Yay, that worked! 🎉  That's way cleaner, and I agree, I'd rather not have another config option.

A separate piece of feedback: I tried unsuccessfully last week to set a custom preview controller, but I was looking at [the configuration page](https://v2.lookbook.build/guide/config_reference#preview_controller), which only shows `config.lookbook.preview_controller`. I see now that the [view component page](https://v2.lookbook.build/guide/components/view_component#previews) documents that there's a separate view component `preview_controller`, but I didn't notice it there when looking at the preview controller documentation. Maybe it's worth duplicating on the configuration page where you can use either? Or maybe I need to read the manual more closely.  😄 

Thanks for the speedy help, I really appreciate it!

**Comment by allmarkedup** [comment]
@ksweetie excellent! Glad that fixed it. And yes you are right - the duplication of the ViewComponent config is unfortunately a bit confusing and should definitely be documented better. I'll add a note to improve that. Ideally setting either would work both ways (for Lookbook and ViewComponent) but that is a bit tricky... may be worth revisiting though.

I'll close this issue down now then but if you run into any other issues just let me know 🙂

**Comment by fredboyle** [comment]
@ksweetie We have a similar setup but my Rails Engine knowledge is not very broad. Would you be willing to share an example config of how you had this setup functioning so you could load the mounted engine's Lookbook in the "main app"?

I've tried several things but am only able to get things functioning and accessible in the mountable engine/gem's context and not in the main app that loads the engine.

Thanks for your help.

**Comment by ksweetie** [comment]
@fredboyle Unfortunately, I de-converted our component library from an engine and put it into a namespaced service inside our main app. There were just issues at every turn and I felt like I was going against the grain. That said, I did have Lookbook working. I'm not sure how to help without more info of what error/issue you're seeing though. I can say that you need to register routes in both places:

```rb
# main app routes.rb
mount YourEngine::Engine, at: "/lookbook"

# engine's routes.rb
YourEngine::Engine.routes.draw do
  mount Lookbook::Engine, at: "/"
end
```

**Comment by fredboyle** [comment]
@ksweetie Thanks for the response. Figured the routes thing. My issue is mostly around having Lookbook not cause issues in the main/host app when loading the engine.

Currently I have Lookbook in my engine's gemspec file as a dev dependency, then I require it in the `engine.rb` file. This functions fine in the engine repo.

However after these changes, adding the engine in the main/host app, doing a `bundle install`, then trying to start the Rails server, it errors out due to being unable to locate Lookbook.

Any hints or guidance compared to how you had it when it was functioning for you?
Do you have a git commit you could provide me a snapshot of your engine configuration from when it was an engine?

**Comment by ksweetie** [comment]
Sorry, I don't have anything open source I can share.

Did you try adding Lookbook as a regular dependency? This was from my original commit:

```rb
  spec.add_dependency "lookbook", ">= 2.0.0.beta"
  spec.add_dependency "rails", rails_version
  spec.add_dependency "sprockets-rails", "~> 3.4.0"
  spec.add_dependency "view_component", ">= 2.82.0"

  # Live reloading in Lookbook
  spec.add_development_dependency "actioncable", rails_version
  spec.add_development_dependency "listen", "~> 3.8"
```

```rb
# engines/your_engine/lib/your_engine.rb
require "your_engine/version"

module YourEngine
end

require "lookbook"
require "your_engine/engine"
```

**Comment by fredboyle** [comment]
@ksweetie Thanks for the info. I'll dig into it and see. 

Was trying to avoid having a runtime dependency and only have a development dependency since that's the only time it's needed. Experimentation will tell.

Thanks again for the info and being willing to help me figure it out.
