### ISSUE TITLE
Asset path for icons not namespaced

### ISSUE THREAD

**Issue by svenfinger** [ViewComponent/lookbook#360]
### Describe the bug

Since `2.0.0.beta.5` we started to experience issues with our icons. Some icons were broken, while others were fine. After some investigation we found out that this is caused by an [update to the icons in `2.0.0.beta.5` and the asset path](https://github.com/ViewComponent/lookbook/blob/457d6e60c4bdcd4ec2527c7a4967bd91eebf5598/bin/generate-icons#L46).

In the asset pipeline the Lookbook icons get mixed/screwed with other icons with the same name. If a Gem is defined in the Gemfile (in our case it’s a Rails Engine, see "Additional context" section below) and **it’s defined after Lookbook**, the Gem’s icons will get screwed (Case 1). And vice versa, if a Gem is **defined before Lookbook**, Lookbook’s icons get screwed (Case 2).

### To Reproduce

Steps to reproduce the behavior (by the example of case 1 from above):

1. Provide SVG icons (in our case via a Rails Engine) with the same name as Lookbook’s icons to end up in `/assets/images/icons/` (e.g. `truck.svg` or `check-circle-2.svg`)
2. Use Lookbook `2.0.0.beta.5` **AFTER** any other Gems that place icons in this path
3. Serve assets (to visualize this in the directory tree you can use `rails assets:precompile`, but it also happens with just using the Rails cache in development for example)
4. The icons in the base directory `/assets/images/icons/` get screwed with Lookbook’s icons

### Expected behavior

Lookbook icons ending up in a dedicated/namespaced directory (e.g. `/assets/images/icons/lookbook/`) and not directly into `/assets/images/icons/` to not interfere with other project icons.

### Screenshots
<img width="306" alt="Screenshot 2023-03-17 at 09 25 02" src="https://user-images.githubusercontent.com/1543655/225856386-9a6894f8-1f3b-419f-add2-312956594e67.png">

### Version numbers 

Please complete the following information:

* Lookbook: `2.0.0.beta.5`
* ViewComponent: `2.82.0`
* Rails: `7.0.4.3`
* Ruby: `3.2.0`

### Additional context

```
[1] (development) (main)> Rails.application.config.assets.paths
=> ["/Users/svenfinger/Projects/zai-procurement/app/assets/builds",
 "/Users/svenfinger/Projects/zai-procurement/app/assets/config",
 "/Users/svenfinger/Projects/zai-procurement/app/assets/images",
 "/Users/svenfinger/Projects/zai-procurement/app/assets/stylesheets",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/turbo-rails-1.1.1/app/assets/javascripts",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/lookbook-2.0.0.beta.5/app/assets/lookbook",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/view_component-2.82.0/app/assets/vendor",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-ui-12.4.1/vendor/assets/fonts",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-ui-12.4.1/vendor/assets/images",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-ui-12.4.1/vendor/assets/stylesheets",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-toolkit-3.2.2/app/assets/config",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-toolkit-3.2.2/app/assets/stylesheets",
 "/Users/svenfinger/Projects/zai-procurement/connect/app/assets/config",
 "/Users/svenfinger/Projects/zai-procurement/connect/app/assets/images",
 "/Users/svenfinger/Projects/zai-procurement/connect/app/assets/stylesheets",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ahoy_matey-4.2.1/vendor/assets/javascripts",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled"]
```

As you can see above, in our case we serve icons via our own Gem that is a Rails Engine, too:
`"/Users/svenfinger/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zaikio-ui-12.4.1/vendor/assets/images",`
These icons also land in `/assets/images/icons/` and then get screwed by the Lookbook icons.

**Comment by allmarkedup** [comment]
@svenfinger Apologies for this and thanks for letting me know - I'm out for a couple of hours now but will get this fixed as soon as I'm back. None of Lookbook's assets should really be accessible to the asset pipeline as they are all prebuilt and served statically at a different URL so I'll move the whole asset folder to prevent any other conflicts.

I'll let you know as soon as I've shipped a fix, sorry to cause you a problem with this!

**Comment by svenfinger** [comment]
@allmarkedup Thank you for the fast response and don’t worry, we can work around this until a fix is available. 🙂

**Comment by allmarkedup** [comment]
hey @svenfinger - I've just released beta.6 that should fix this issue. Thanks again for bringing it to my attention (and the detailed info) and let me know how you get on with it when you've given it a try.

**Comment by svenfinger** [comment]
@allmarkedup Wow, that was crazy fast! I gave it a try and it works. Thank you. 😄

**Comment by dhnaranjo** [comment]
@allmarkedup I think that this release was packaged without the assets folder

```
dazmin@Desmonds-MacBook-Pro mmx % less Gemfile.lock | grep lookbook
    lookbook (2.0.0.beta.6)
  lookbook (= 2.0.0.beta.6)
dazmin@Desmonds-MacBook-Pro mmx % cd $(bundle show lookbook)       
dazmin@Desmonds-MacBook-Pro lookbook-2.0.0.beta.6 % ls
LICENSE.txt     README.md       app             config          lib             public
dazmin@Desmonds-MacBook-Pro lookbook-2.0.0.beta.6 % cd app
dazmin@Desmonds-MacBook-Pro app % ls
components      controllers     helpers         views
dazmin@Desmonds-MacBook-Pro app % pwd
/Users/dazmin/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/lookbook-2.0.0.beta.6/app
dazmin@Desmonds-MacBook-Pro app % 
```

Loading lookbook gives

```
RuntimeError in Lookbook::Application#index

Showing /Users/dazmin/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/lookbook-2.0.0.beta.6/app/views/layouts/lookbook/application.html.erb where line #14 raised:

`check` is not a valid icon name
```

**Comment by allmarkedup** [comment]
@dhnaranjo beta.7 is up now that should hopefully work fix this - sorry about that!

@svenfinger I'm not sure how come beta.6 was working for you but I'd recommend upgrading to beta.7 to prevent any more issues.

Any other problems with this just let me know, thank you :-)

**Comment by dhnaranjo** [comment]
Confirm'd good. Appreciate you.
