### ISSUE TITLE
Lookbook assets fail to load if a relative_url_root has been configured

### ISSUE THREAD

**Issue by KaptajnKold** [ViewComponent/lookbook#362]
### Describe the bug

In a Rails projects, if a relative_url_root (e.g. `/my-app`) is specified, the Lookbook assets (stylesheets, javascript) fail to load. Instead of loading them from `/my-app/lookbook-assets/...` where they are available, it tries to load them from `/lookbook-assets/...` where they are not.

### To Reproduce

* Create a new Rails app.
* Add Lookbook to its Gemfile.
* In `config/application.rb`, specify a relative_url_root: `config.relative_url_root = '/my-app'`
* In routes.rb, mount the lookbook engine at a relative (not absolute!) path: `:mount Lookbook::Engine, at: "lookbook"`
* Start the server and navigate to `localhost:3000/my-app/lookbook`
* Notice how all the styling and behavior is missing.

### Expected behavior

The expected behavior is the styling and behavior is not missing.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta.5
* ViewComponent: 2.77.0
* Rails: 6.1.7
* Ruby: 3.2.1

**Comment by allmarkedup** [comment]
Thanks for this @KaptajnKold - `relative_url_root` was not a config option I was aware of. I'll get this fixed to ensure Lookbook respects that setting when serving assets.

**Comment by KaptajnKold** [comment]
I can confirm that it works perfectly now. Thanks for the effort!

**Comment by allmarkedup** [comment]
Great! Thanks for letting me know 🙂
