### ISSUE TITLE
Support for non-standard directory structure

### ISSUE THREAD

**Issue by ksweetie** [ViewComponent/lookbook#375]
### Is your feature request related to a problem? Please describe

Hey! I don't expect you to fix this, since it's very much an edge case, but figured I would open an issue in case there was a simple fix.

I'm spiking out a new component library, and I wanted a directory structure that had these two properties:

1. Every file for a component is in the same directory.
2. To call the component, you don't need to add an extra `::Component` or repeat the component name. ie, `Button.new` instead of `Button::Component.new` or `Button::Button.new`.

To accomplish the above, I'm using Zeitwerk to collapse component directories, which so far is working really well. However, it's confusing Lookbook, specifically the sidebar nav and the URL:

```rb
# the badge directory is collapsed via Zeitwerk, component is used via `Badge.new`
/components/badge/badge.rb
/components/badge/badge.html.erb
/components/badge/badge_preview.rb

# Usage
Badge.new(text: "My Badge")
```

<img width="183" alt="Screen Shot 2023-03-22 at 3 37 43 PM" src="https://user-images.githubusercontent.com/2036284/227044524-5ddb5f1b-c93a-4c0a-8130-fc15ad588f58.png">

### Describe the solution you'd like

I'm not sure, maybe Lookbook shouldn't create a folder nav item if it's identical to the preview name? ie `[component]/[component]_preview`. I'm not sure if that would be unexpected behavior for others though.

### Describe alternatives you've considered

My monkey patch is pretty simple. It fixes the sidebar, but the URL still has duplicated component name.

```rb
module Lookbook
  class PreviewEntity
    def file_name_base
      @_file_name_slug ||= file_name(true).gsub(/[\w_]+?_preview$/, "")
    end

    def depth
      lookup_path.split("/").size - 1
    end
  end
end
```

### Additional context

No hard feelings if this isn't something you want to support. I just wanted to put it on your radar in the off chance that there was a simple solution. Thanks for checking it out!

**Comment by allmarkedup** [comment]
Hi @ksweetie and thanks for the feature request.

This is actually something I'd love to support (and to use myself) - and I suspect we are not alone amongst ViewComponent users in wanting to remove the `Component` suffix ;-)

The solution your propose _might_ work in this specific case (component the same name as the directory) although I'll have to have more of a think about if it might cause any other issues down the line. However I would definitely prefer to have a more generic solution - one that maybe uses Zeitwerk itself to figure out what paths are collapsed and then uses those for the components. I've not delved deep into Zeitwerk before but I imagine it must be possible to figure out what would be needed.

You've definitely piqued my interest with this one so i'll have a tinker when I get a chance. If I find a way to implement it then it would be a post-2.0-launch addition however as I don't want to mess with things like class loading at this late stage.

In the meantime, if you wanted a more mundane fix you could always separate your previews from you components - I personally prefer something like the approach you outline above (i.e. preview within the component directory) but having the previews in their own previews directory can often mean more flexibility with how the component library is _presented_ even if the components themselves are organised slightly differently.

So something like

```
path/to/previews/
├── button_preview.rb
└── badge_preview.rb
```

would give you the structure you are after, albeit at the expense of keeping everything nicely together. Just a thought anyway :-)

I'll let you know when I have had a chance to investigate this a bit more but hopefully it'll be possible to figure something out to get support for this into Lookbook. Thanks again for the suggestion!

**Comment by allmarkedup** [comment]
> If I find a way to implement it then it would be a post-2.0-launch addition however as I don't want to mess with things like class loading at this late stage.

@ksweetie Well... I did say the above _but_ I really liked this idea and I couldn't resist having a tinker 😄 After I had a bit more of a think about it I realised that it was probably going to be simpler than I first thought, no need to try and lookup paths from the Zeitwerk instance or anything.

So... I've just had a go and I believe I've got it working, but it would be great if you were able to confirm with the setup you have been experimenting with.

To test you'll need to pull in Lookbook directly from the `collapsed-preview-paths` branch of this repo like this:

```rb
# Gemfile
gem "lookbook", git: "git://github.com/ViewComponent/lookbook.git", branch: "collapsed-preview-paths"
```

I've been using your badge example (badge component folder at the root of the `app/components` directory) and then collapsing down the path by adding the following in the `application.rb`:

```rb
Rails.autoloaders.main.collapse("app/components/*")
```

With the changes that all seems work nicely for me now. I've also experimented with nesting components deeper within the components directory and collapsing some interim hierarchy and that seems to work too.

If you get a chance to give it a try it that would be great, and let me know if you run into any issues at all. I'm pretty sure this change won't have any negative downstream consequences but I'll keep testing at my end too to make sure.

Once we are confident it's all working I'll merge it in and get it out in the next release. And _then_ I'm going to feature-freeze until v2.0 is out properly (although I've lost track of how many times I've said that now... 🙄)

**Comment by ksweetie** [comment]
Wow, I wasn't expecting you to implement this, and so quickly! I just gave it a spin and it worked perfectly 🎉!  I love the solution, much cleaner than I was expecting.

One minor note: I have all of my components nested under a namespace, so they're all called via `Foo::Badge.new`. Since every component is nested inside this namespace, it's kind of unnecessary to show in the nav. To get rid of it, I set `preview_paths` to `app/components/foo`. However, it looks like that no longer has an effect on this branch:

```
# 2.0.0.beta.7
Badge
  Badge
    Example

# collapsed-preview-paths
Foo
  Badge
    Example
```

That's very minor though, and I do think it makes sense. It's a small tradeoff to remove that monkey patch.

Thanks for working on this, I really appreciate it!

**Comment by allmarkedup** [comment]
@ksweetie thats great! I'll get it out in the next release then, hopefully today or tomorrow.

That is interesting about the top level namespace issue though - I think that is because the preview path is now being assembled from the class name rather than using the relative path filesystem path. But it shouldn't walk back above the component directory root. I'll see if I can fix that quickly now.

I tried out your component organisation pattern out myself on a different project this morning - I really like it! I normally organise component files something like this:

```
app/
└── components/
    └── button/
        ├── component.rb
        ├── component.html.erb
        └── component.css
```

Which is similar to your approach.... but vastly inferior! All components have a nasty `::Component` suffix on them and every file in my editor is just called 'component' which isn't great at all. I don't know why I never thought of leaning on Zeitwerk (I use it to handle all the autoloading in Lookbook) but I appreciate you sharing the suggestion here, I think this will be my new default going forwards 🙂

**Comment by ksweetie** [comment]
Haha, yeah I went down several rabbit holes trying to make it work exactly like I wanted. I was so excited when the Zeitwerk collapse spike did worked. I'm surprised I haven't seen anyone else mention doing it. Admittedly, it's arguably confusing to have files declare constants that don't exactly match their directory structure (in a Rails app anyway), but I feel like the nice component signature makes it worth it. I'm glad it was helpful for you as well!

**Comment by allmarkedup** [comment]
> Admittedly, it's arguably confusing to have files declare constants that don't exactly match their directory structure (in a Rails app anyway)

Pretty sure Rails sneaks a bit of that in anyway so I reckon it's acceptable ;-)

I've just come across a bit of an issue with the new preview path resolving code so I'm going to hold off shipping a new release until I'm confident that I've fixed it. Shouldn't be too long though.

**Comment by allmarkedup** [comment]
@ksweetie I've just released version [rc1](https://github.com/ViewComponent/lookbook/releases/tag/v2.0.0-rc.1) that includes this feature. I had to do a bit of last-minute wrangling to ensure backwards compatibility with all preview file setups - it should still work fine with the autoloader too but if you run into any problems just let me know.

I'll close this issue down now then - thanks again for the feature suggestion and good luck building out your component library 🙂

**Comment by ksweetie** [comment]
I tested rc1 and it looks good to me. Thanks for making this even better!

**Comment by allmarkedup** [comment]
@ksweetie excellent, and my pleasure! :-)
