### ISSUE TITLE
HTML for preview is getting escaped

### ISSUE THREAD

**Issue by jewls618** [ViewComponent/lookbook#382]
I am trying to implement Lookbook to be able to preview ViewComponents. I followed the documentation to use a custom layout for the previews, which looks like:

app/views/layouts/preview.html.erb

```
<!DOCTYPE html>
<html>
<head>
  <title>Component Preview</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_packs_with_chunks_tag 'main', media: 'screen, projection', 'data-turbo-track': 'reload' %>
  <% content_for :top_header do %>
    <% submit_meta_tags %>
  <% end %>
</head>
<body>
  <div class="p-4">
    <div class="mx-auto" style="max-width: <%= lookbook_display(:max_width, "100%") %>">
      <%= yield %>
    </div>
  </div>
</body>
</html>
```

However, what we see from the yield is just plain text (see screenshot below). It seems as though it's showing the entire app/views/layout/preview.html.erb contents into its own preview layout.

The default is being set up with the [view_component] like so:`config.view_component.default_preview_layout = "preview"`

There are no errors in the console. 

### Config Options

```
    config.lookbook.preview_paths = "#{Rails.root}/spec/components/previews"
    config.view_component.default_preview_layout = "preview"
    config.lookbook.ui_favicon = false
    config.lookbook.ui_theme_overrides = {
      header_bg: "#002d74"
    }
```

### Expected behavior

Expected to see the button instead of the HTML of the html.erb file.

From looking at the `render_example_to_string()` method, it looks as though it renders to a string but never gets turned into html.

### Screenshots
<img width="1183" alt="Screen Shot 2023-03-28 at 1 22 58 PM" src="https://user-images.githubusercontent.com/19556185/228319230-23894bba-406a-43e3-a84b-4adb5944ad73.png">
<img width="1183" alt="Screen Shot 2023-03-28 at 1 22 58 PM" src="https://user-images.githubusercontent.com/19556185/228319313-9d1f8436-ed5f-476a-bf36-41e4a53dd55b.png">

### Version numbers 

* Lookbook: 2.0.0.beta.8
* ViewComponent: 2.62.0
* Rails: 6.1.7.2
* Ruby: 2.7.7

#### Any help deciphering whether this is a bug within the `render_example_to_string()` method or maybe a local configuration issue would be greatly appreciated!

**Comment by jewls618** [comment]
Come to find out, the issue is due to another gem conflicting with lookbook. The gem 'remotipart' is overriding render with something that breaks the preview for Lookbook.

**Comment by allmarkedup** [comment]
@jewls618 Thanks for updating the issue after figuring it out. I hope you've found a workaround!
