### ISSUE TITLE
Use a datepicker library rather than `<input type "datetime-local">`

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/lookbook#385]
### Is your feature request related to a problem? Please describe

The date picker closes after each click in Chromium-based browsers, which makes it annoying to use. It seems to be updating the bound value immediately, causing the component preview to update, which closes the picker.

In Safari and Firefox, it does not show the time even when the type is set to `datetime-local`. You _can_ change month without it closing the picker, though.

Even when the preview defaults a param to `Time.zone.now`, Lookbook shows a blank datetime and requires _all_ fields to be filled, which is an annoyance:

![image](https://user-images.githubusercontent.com/139183/229073394-53d7dea7-dbc3-4ec9-af83-1d74fa49d29e.png)

### Describe the solution you'd like

Rather than using `<input type="datetime-local">`, could Lookbook use a basic datepicker library that would be the same across browsers? Ideally, it wouldn't update the value until the user dismisses the picker by clicking outside it (or clicking an OK button).

### Describe alternatives you've considered

Ignoring the picker popup and entering the values into the field manually seems to be the only way of entering a time on Firefox and Safari — and it's quicker than having to keep reopening the picker in most cases in Chromium.

#### Vivaldi (also Brave, presumably all Chromium-based browsers)

https://user-images.githubusercontent.com/139183/229065184-30978d70-ae57-4521-a934-324ebac9d826.mov

#### Safari

![image](https://user-images.githubusercontent.com/139183/229067419-371ba83e-cb25-4192-a746-11bf6bd6c2f4.png)

#### Firefox

![image](https://user-images.githubusercontent.com/139183/229067511-6a99e184-c5c2-47bd-a737-331b45b697b8.png)

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta.9
* ViewComponent: 2.82.0
* Rails: 6.0.5.1
* Ruby: 2.7.4p191 (2021-07-07 revision a21a3b7d23) [aarch64-linux]

**Comment by allmarkedup** [comment]
@unikitty37 Yes you are right, a consistent date/time picking experience across browsers would be great. I'll add it to the list!

The fact that the picker closes after every click is really a bug though - I'll try and fix that as a separate piece of work.

In the meantime, if you wanted to have a go at implementing your own custom date/time picker input, there are some docs on how to do that here: https://v2.lookbook.build/extend/inputs - would love some feedback on the process if you do give it a try!

**Comment by allmarkedup** [comment]
Hey @unikitty37, just to let you know that I've now fixed the two issues you mentioned:

1) Default values not being applied to the field automatically 
2) Picker closing and updating after every click

Date (and datetime local) pickers now require a second 'save' step to apply the changes (either by clicking the save button or pressing enter in the field), so the picker can stay open for as long as needed. I've attached a short video of the new behaviour below:

https://user-images.githubusercontent.com/126726/229396394-c047fbac-a0c1-4476-8201-478bf010980c.mp4

It would definitely be nice to have a consistent date picking experience between browsers (using a third-party picker) but hopefully these changes will make the date picking experience a bit less frustrating in the meantime.

The changes have not gone out on a release yet (although the are in the v2 branch if you wish to pull that down) but I'll update here when the next release goes out, should be in the next day or two.

Appreciate you bringing this to my attention and let me know how you get on if you give it a spin.

**Comment by allmarkedup** [comment]
@unikitty37 the date picker fixes have also gone out in the latest release ([rc1](https://github.com/ViewComponent/lookbook/releases/tag/v2.0.0-rc.1)) so I'll shut this issue down too, if you are okay with that? I may revisit putting in a custom JS datepicker at some point in the future but I think these fixes make the browser-natives ones pretty usable too.

If you are very keen then feel free to reopen and I'll try to get back to it once the proper v2 release has shipped :-)
