### ISSUE TITLE
lib directory autoloading issue

### ISSUE THREAD

**Issue by allmarkedup** [ViewComponent/lookbook#386]
After installing Lookbook @unikitty has run into some odd autoloading behaviour in their `lib` directory. More details here: https://github.com/ViewComponent/lookbook/issues/383#issuecomment-1491493541

**Comment by unikitty37** [comment]
I've just tried beta.4 and got the same error as with beta.8, so it looks like the changes in beta.5 aren't to blame.

**Comment by allmarkedup** [comment]
Okay thanks @unikitty37, appreciate you giving it a try. I haven't been able to replicate any lib directory strangeness here yet but I'll keep trying :-)

**Comment by allmarkedup** [comment]
I'm going to close this down for now as I'm afraid I've not been able to replicate and haven't heard any other reports of anything that might be related. It may be some conflict with a project-specfic autoloader config and Lookbook's own autoloader but I'm not sure I can make any more progress on it without a more concrete example.

Please do reopen if there is anything to add to this at any time or if anyone else runs into a similar issue.
