### ISSUE TITLE
`f` keyboard shortcut should check no modifier keys are pressed

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/lookbook#388]
> **Before opening an issue** please make sure you have consulted the [Lookbook documentation](https://lookbook.build) (in particular the [Troubleshooting section](https://lookbook.build/guide/troubleshooting/)) and have checked the existing issues to see if this has already been reported.

### Describe the bug

The search box has `@keydown.f.stop.prevent.window="focus"` on it, but this also activates when pressing ⌘F to search within the page, meaning going to the menubar when I need to find something in the page. 

### To Reproduce

1. Go to a component preview in Lookbook
2. Press ⌘F (or ⌃F if not on macOS)
3. The search field in the page is focused

### Expected behavior

The search field in the page is not focused, and the browser's own find-in-page function is invoked.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta.9
* ViewComponent: 2.82.0
* Rails: 6.0.5.1
* Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [aarch64-linux]

### Additional context

It looks like alpine.js doesn't support exact keystrokes: https://github.com/alpinejs/alpine/issues/273

From what I've seen in that conversation I'm guessing the workaround would be something like this:

`<input @keydown.f.window="if (!($event.shiftKey || $event.metaKey || $event.ctrlKey || $event.altKey)) { focus; $event.preventDefault; $event.stopPropagation }" …>`

…but I don't know enough about Alpine to be certain my syntax is correct. It doesn't allow me to change it in the inspector, so I can't test it without building a custom copy of the gem, and I'm a bit short of time for that 😁

**Comment by allmarkedup** [comment]
@unikitty37 yes good suggestion, thank you. I'll see if I can get a fix done tonight so it can go out in the next release with the date picker improvements 👍
