### ISSUE TITLE
undefined method `shift_path' for #<ActionView::Base:0x0000000000cdf0>

### ISSUE THREAD

**Issue by robinator** [ViewComponent/lookbook#399]
### Describe the bug

I have just started using Lookbook beta and I'm attempting to use it with regular ActionView partials.  Rendering boring partials works fine but I am getting errors if the partial contains urls or paths:

Rendering a menu:
```
  = link_to work_url, class: 'button is-medium'
```
Results in
```
undefined local variable or method `work_url' for #<ActionView::Base:0x000000000118f0>
```

Similarly, rendering a form:
```
  = form_for(shift) do |f|
```
results in 
```
undefined method `shift_path' for #<ActionView::Base:0x0000000000cdf0>
```

### To Reproduce

Try to render an ActionView template with link_to in it.

### Expected behavior

It should render the partial normally.

### Version numbers 

Please complete the following information:

* Lookbook: `lookbook-2.0.0.rc.1`
* ViewComponent: `view_component-2.82.0`
* Rails: `rails-7.0.4.3`
* Ruby: `3.2.0`

### Additional context

Please let me know if I should be including something else or am otherwise configuring it incorrectly.

**Comment by robinator** [comment]
I'm not sure if this is related to what is mentioned here: https://v2.lookbook.build/guide/troubleshooting, but I do have a custom layout without links and the error is coming from the partials themselves.

**Comment by robinator** [comment]
Interestingly, it started working when I set my own controller:
```
Rails.application.configure do
  config.lookbook.preview_controller = "PreviewController"
end

class PreviewController < ViewComponentsController
  helper Lookbook::PreviewHelper
end
```

**Comment by allmarkedup** [comment]
Hey @robinator thanks for this. You are correct - this is related to the issue in the troubleshooting docs, but the good news is that I believe I (finally) have a fix in this PR: https://github.com/ViewComponent/lookbook/pull/403

When you have a chance, could you pull in Lookbook from the `v2-fix-url-helpers` branch and see if it fixes the issue (when using the default preview controller)?

```rb
gem "lookbook", git: "git://github.com/ViewComponent/lookbook.git", branch: "v2-fix-url-helpers"
```

I'm just doing a bit more testing myself but it would be great to know if this works for you - many thanks!

**Comment by robinator** [comment]
Hi @allmarkedup!  Thanks for digging into this, however I am still getting the same errors as above on the new branch using the default preview controller.

**Comment by allmarkedup** [comment]
@robinator well that is disappointing 😂 Thought I had finally fixed it.

It definitely works for me in some of the apps I was having issues with previously, but clearly this fix is not the whole story. I'll see if I can take another stab at it.

Thanks for giving it a test and I'll let you know when I have something else to try.

**Comment by robinator** [comment]
Hey @allmarkedup, I was doing some [research](https://github.com/richpeck/exception_handler/blob/e13d5df2a49e1dc7d96af7e921e013857c0700d8/app/controllers/exception_handler/exceptions_controller.rb#L30) last night and was able to find a fix for this particular issue (although I have no idea if it's appropriate for the gem 😂).  Including the main application's route helpers did the trick on a "stock" lookbook install:

```ruby
module Lookbook
  module PreviewControllerActions
    extend ActiveSupport::Concern

    included do
      helper PreviewHelper
      helper Rails.application.routes.url_helpers
      ...
    end
end
```

I can also try to put up a patch if you think that's better.

**Comment by allmarkedup** [comment]
@robinator I missed your comment just now but have just pushed an update to the PR with this exact change. Great minds and all that ;-)

I think it is totally appropriate to ensure the template is rendered with access to the host app's url helpers. What I haven't quite figured out is why some apps already seem to have access to them without explicitly including them like this and some don't. But there is no downside to explicitly including them like this as far as I can tell.

The PR branch has been updated already so if you could just confirm that now works that would be fantastic.

Really appreciate you taking the time to dive in and figure this one out, much appreciated :-)

**Comment by allmarkedup** [comment]
@robinator Fantastic, I'll get that merged in now then and out in the next release.

> In terms of some apps working and others not, are you referring to the dummy app? 

No, in some apps (like ours at work) the URL helpers already seem to be accessible to the previews without this change. But it's no big deal at all, just glad to have this fixed now. Thanks again :-)
