### ISSUE TITLE
Lookbook engine sometimes hangs when changing params in preview

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/lookbook#401]
> **Before opening an issue** please make sure you have consulted the [Lookbook documentation](https://lookbook.build) (in particular the [Troubleshooting section](https://lookbook.build/guide/troubleshooting/)) and have checked the existing issues to see if this has already been reported.

### Describe the bug

In some circumstances, the Lookbook engine will hang, requiring the Rails server to be restarted. Non-Lookbook pages still render as normal.

#### table_component_preview.rb

```ruby
# frozen_string_literal: true

class TableComponentPreview < Lookbook::Preview
  # @param col_a text
  # @param col_b text
  # @param col_c text
  # @param col_d text
  def default(col_a: 'Col 1', col_b: 'Col 2', col_c: 'Col 3', col_d: 'Col 4')
    render TableComponent.new do |table|
      table.header { col_a }
      table.header { col_b }
      table.header { col_c }
      table.header { col_d }
    end
  end
end
```

#### table_component.rb

```ruby
# frozen_string_literal: true

class TableComponent < ApplicationComponent
  renders_many :headers, Table::HeaderComponent
end
```

#### table_component.html.erb

```html
<table>
  <thead>
    <% headers.each do |header| %>
      <%= header %>
    <% end %>
  </thead>
  <tbody>
  </tbody>
</table>
```

#### table/header_component.rb

```ruby
# frozen_string_literal: true

module Table
  class HeaderComponent < ApplicationComponent
  end
end
```

#### table/header_component/header_component.html.erb

```html
<th scope="col">
  <%= content %>
</th>

```

* Click on Table in the list of Lookbook previews.
* The table will render.
* Start changing the parameters. It seems to happen more readily when typing quickly.
* At some point, Lookbook will stop responding. The spinner at top right will not go away, the fields will not be updated, and selecting a different preview from the left-hand pane will not change what's on screen. The Preview/HTML selector continues to work (presumably both panes are already in the DOM and it's just toggling visibility). Reloading the page (with or without the cache cleared) does not produce a response. Non-Lookbook pages continue to load normally. The only way to get Lookbook to respond is to restart Rails. There are no errors in the console.

### Expected behaviour

The table headers in the preview update and Lookbook continues to respond to input.

### Screenshots

![image](https://user-images.githubusercontent.com/139183/230121106-45a44c5e-bd7b-443d-985c-53bf0e4bfe92.png)

![image](https://user-images.githubusercontent.com/139183/230130063-3c372859-7dc4-4195-9992-5b09c1ea141c.png)

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.rc.1
* ViewComponent: 2.82.0
* Rails: 6.0.5.1
* Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [aarch64-linux]

### Additional context

I've also had similar behaviour when RubyMine has "helpfully" autosaved an in-progress preview despite my having turned autosaving off, so I have `config.lookbook.live_updates = false` to stop it reloading something that's not actually valid; otherwise, the only config changes are `project_name` and `ui_theme_overrides`.

The hanging on autosave occurred in beta.8 and onwards (and may have been in earlier versions, but this is the first I used) but I assumed this was just because RubyMine was saving invalid code. I've only just written this preview, so I've only tested it against rc.1 so far.

**Comment by allmarkedup** [comment]
@unikitty37 Thanks for all the detail on this! I've spun up fresh Rails 6 project and added the components and previews as above but I've not yet been able to recreate this. I'll keep trying though - there must be something going on with the number of requests being made (which can be quite a lot of typing quickly in the param fields) vs the time it takes for the response to be rendered, or something along those lines.

Interesting about the auto save with (potentially) invalid code too - I'll take a look at that as well.

Out of interest, which webserver are you using - just the default Puma one that ships with Rails? Or something else? May not have anything to do with it but might help me recreate the issue here if you are using something more custom.

**Comment by unikitty37** [comment]
Sorry, I just noticed you'd replied. It's the default Puma.
