### ISSUE TITLE
The action ‘render_scenario_to_string’ could not be found for ViewComponentsController

### ISSUE THREAD

**Issue by NYDrewReynolds** [ViewComponent/lookbook#419]
**Versions**
Rails: '6.1.4.4'
Lookbook: '2.0.0.rc.2'
ViewComponent: '~> 3.0.0.rc2'

**Description**
After upgrading to `'2.0.0.rc.2'` began seeing this bug when in our production environment. It is the same across browsers. It is the same error across all components, previews, and scenarios.

The error message: `The action ‘render_scenario_to_string’ could not be found for ViewComponentsController Did you mean? ` followed by some internal path suggestions.

**Comment by allmarkedup** [comment]
Hey @NYDrewReynolds - sorry about this, this issue is actually be fixed already on the `v2` branch but I just haven't published a new release yet, been a busy week. I'll merge your PR and then try to get one out later today!

**Comment by allmarkedup** [comment]
@NYDrewReynolds this is now fixed in the 2.0.0.rc.3 release so I'm going to close this now. Any problems still just let me know!
