### ISSUE TITLE
Preview controller shouldn't be memoized

### ISSUE THREAD

**Issue by ksweetie** [ViewComponent/lookbook#421]
### Describe the bug

I have a preview controller that looks this:

```rb
class PreviewController < ActionController::Base
  include ViewComponent::PreviewActions

  default_form_builder MyFormBuilder
end
```

However, changing the form builder doesn't result in the change in Lookbook—a full server restart is required. I think that's due to the memoization [here](https://github.com/ViewComponent/lookbook/blob/v2/lib/lookbook/engine.rb#L204), though I haven't verified that.

### Expected behavior

Changing a file should be reflected on page reload without needing to restart the server.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.rc.1
* ViewComponent: 2.82.0
* Rails: 7.0.4.3
* Ruby: 3.2.2

I'm not sure if my use case is unintended, or if others are seeing a benefit from memoizing this class. Thanks for the consideration!

**Comment by allmarkedup** [comment]
Hey @ksweetie thanks for the heads up on this - I haven't had much spare time recently but I'll try to look at this as soon as I can. TBH I suspect we can just remove the memoization without any bother!
