### ISSUE TITLE
Reflected XSS Vulnerability in Lookbook

### ISSUE THREAD

**Issue by ChrisNJ58** [ViewComponent/lookbook#435]
### Describe the bug

There is a reflected XSS vulnerability on endpoints within Lookbook.

### To Reproduce

It can be reproduced on the current heroku demo app by clicking [this link](https://lookbook-demo-app.herokuapp.com/lookbook/inspect/elements/button/%3Cimg%20src=x%20onerror=alert(1)%3E) (https://lookbook-demo-app.herokuapp.com/lookbook/inspect/elements/button/%3Cimg%20src=x%20onerror=alert(1)%3E)

### Expected behavior

That the html values provided by users are sanitized prior to them being put into the page.

### Screenshots

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/57690976/234125010-40f0de78-1440-4e69-8bbd-c24c7ad395db.png">

### Version numbers 

In addition to the heroku demo app, I can confirm it is also active on the following version I have tested locally:

* Lookbook: 1.1.0
* ViewComponent: 2.82
* Rails: 6.1.6
* Ruby: 2.6.10

**Comment by allmarkedup** [comment]
Thanks for the heads up on this @ChrisNJ58 - I'll get this fixed up and a new release out asap.

**Comment by allmarkedup** [comment]
@ChrisNJ58 this is now fixed and released in v1.5.4 (and demo site updated). Thanks again for the heads up 👍
