### ISSUE TITLE
ArgumentError: wrong number of arguments (given 0, expected 1..3)

### ISSUE THREAD

**Issue by guillaumebriday-pa** [ViewComponent/lookbook#488]
### Describe the bug

My lookbook only works in development env. I follow these instructions https://lookbook.build/guide/installation and it works perfectly but whenever I tried to run in it in test or any other env, I got the error below without any further details.

Any idea why?

Thanks in advance

### Screenshots
<img width="548" alt="Screenshot 2023-06-14 at 14 02 52" src="https://github.com/ViewComponent/lookbook/assets/89008587/8d631d9b-f65e-4e69-826b-fa599e5e007a">

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.5
* ViewComponent: 2.82.0
* Rails: 7.0.5
* Ruby: 3.0.4

**Comment by Spone** [comment]
Hi @guillaumebriday-pa! What's at line 7 in your environment.rb?

**Comment by guillaumebriday-pa** [comment]
```ruby
# frozen_string_literal: true

# Load the Rails application.
require_relative "application"

# Initialize the Rails application.
Rails.application.initialize!  # <-- THIS
```

So it does not really help me to find the root cause :/

**Comment by allmarkedup** [comment]
Hey @guillaumebriday-pa, I'm afraid I can't replicate this at all and don't really know how to investigate it any further I'm afraid :(

I realise it's been a long time since you opened this issue and I'm sorry I can be of more help. I'm going to close this issue but if you have any additional info to share that could give me some clues then feel free to reopen it at any time.

**Comment by guillaumebriday-pa** [comment]
Hi @allmarkedup 

I dived into the issue and found something that might help

The problem comes from this line: https://github.com/ViewComponent/lookbook/blob/main/lib/lookbook/engine.rb#L74

<img width="1440" alt="Screenshot 2023-09-25 at 12 20 28" src="https://github.com/ViewComponent/lookbook/assets/89008587/a80b23e4-a8e6-4d71-a772-c03de6dbc020">

For some reasons it only works in development

**Comment by guillaumebriday-pa** [comment]
<img width="1440" alt="Screenshot 2023-09-25 at 12 20 37" src="https://github.com/ViewComponent/lookbook/assets/89008587/46480e0f-3268-47c8-8367-8f02fea183b4">

`Engine.load_previews` causes the issue

**Comment by guillaumebriday-pa** [comment]
<img width="883" alt="Screenshot 2023-09-25 at 12 34 41" src="https://github.com/ViewComponent/lookbook/assets/89008587/ad1e8915-4bbb-49f9-ad59-03736366e124">

And here is the real problem I guess

**Comment by allmarkedup** [comment]
@guillaumebriday-pa okay thanks for digging into this a bit more. 

`reloaders.execute` should never be called in production, only in development, as there should be no file watching happening in production.

I'm not sure why it would be causing an argument error if it was running but it's worth just making sure that is disabled correctly.

In your `config/environments/production.rb` file can you try setting the [`reload_on_change`](https://lookbook.build/guide/config#reload_on_change) config option to `false`?

```rb
config.lookbook.reload_on_change = false
```

That setting is not normally needed but it should ensure that the reloaders are not running, even if Lookbook's logic for determining when to watch files is not working in this case.

Could you give that a try and see if that makes any difference?

**Comment by guillaumebriday-pa** [comment]
It fails even in test, I changed the config 
```ruby
config.lookbook.reload_on_change = false
``` 

globally in `application.rb` and still fails everywhere :/

**Comment by guillaumebriday-pa** [comment]
Any idea @allmarkedup? 😇

**Comment by allmarkedup** [comment]
@guillaumebriday-pa I'm sorry but I really don't know what is going on here. I can't replicate it myself and I haven't had any other reports of similar issues.

There may be something unique about your particular setup but I'm not sure how I can really progress this I'm afraid :(

**Comment by guillaumebriday-pa** [comment]
Ok I fully understand, let's close it for now, I'll reopen it if I find something! 🙏
