### ISSUE TITLE
Cannot choose display options in an embedded preview

### ISSUE THREAD

**Issue by camertron** [ViewComponent/lookbook#527]
### Describe the bug

Clicking "Display Options" (a gear icon) in an embedded preview doesn't do anything. It seems to work ok when rendered as a preview, i.e. a popover appears and lets me change the display options.

I tried to dig into this today but couldn't figure out how `DisplayOptions::Editor::Component` gets rendered 😢 

### To Reproduce

1. You need to have more than one display option configured.
2. Visit any embed URL.
3. Click on gear icon.

### Expected behavior

The same popover from the preview page should render on the embed page.

### Screenshots

There's not much to show here.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.2
* ViewComponent: 3.5.0
* Rails: 7.0.3
* Ruby: 3.2.0

**Comment by allmarkedup** [comment]
Thanks @camertron! I'll look into this and get it fixed up as soon as I can.

> I tried to dig into this today but couldn't figure out how DisplayOptions::Editor::Component gets rendered 😢

Yeah it's all a bit convoluted in the views at the moment 🥺 would love some time to rework things to make it a bit easier for people to dig into! It's actually rendered here in the embed: https://github.com/ViewComponent/lookbook/blob/317fda7a89bcf0f6dd56a254399525c0341e2d38/app/components/lookbook/embed/inspector/component.html.erb#L21 but I think the issue must be something JS related. I'll check it out and let you know when I've got a fix in place.

**Comment by allmarkedup** [comment]
@camertron I've found the issue and pushed up a fix - will go out in the next release, hopefully later today.

**Comment by allmarkedup** [comment]
This should be fixed now in v2.1.0 so I'm going to go ahead and close this. If you are still have any problems with it just let me know!

**Comment by camertron** [comment]
Awesome, thanks very much for looking into this @allmarkedup!
