### ISSUE TITLE
Support better errors / web console instead of rescuing errors in Lookbook

### ISSUE THREAD

**Issue by wheeyls** [ViewComponent/lookbook#528]
I use better errors in development, and I prefer the experience to the customized error pages that Lookbook provides.

I don't see an option to remove Lookbook's error handling and let me take care of it. Am I missing this, or can it be added?

**Comment by allmarkedup** [comment]
Hey @wheeyls - no I'm afraid this is not possible right now, sorry 😕 I'm aware Lookbook's error handling is not always the best so this would be a really nice feature.

It would be nice if Lookbook could detect if it was being used in the parent app and somehow automatically defer to it for error handing... or even bundle it as the default error handler, perhaps.

I'll leave this issue open as a feature request and try to have a bit of a think about it when I have some time. Thanks for the suggestion!

**Comment by allmarkedup** [comment]
Config option added in #582 (thanks @wheeyls!) has been merged in and will go out in the next release so going to close this down now.
