### ISSUE TITLE
X-Frame-Options always set to deny

### ISSUE THREAD

**Issue by louishuyng** [ViewComponent/lookbook#549]
> **Before opening an issue** please make sure you have consulted the [Lookbook documentation](https://lookbook.build) (in particular the [Troubleshooting section](https://lookbook.build/guide/troubleshooting/)) and have checked the existing issues to see if this has already been reported.

### Describe the bug
In the line where I debug, there is a condition `headers["X-Frame-Options"] == "DENY"`.  To change `headers["X-Frame-Options"]` back to `"SAMEORIGIN"`

The condition can not run  because the value of `headers["X-Frame-Options"]` is in lowercase value `"deny"`

Source code: https://github.dev/ViewComponent/lookbook/blob/main/app/controllers/lookbook/previews_controller.rb

 

### To Reproduce

I think we can add some changes like below to prevent this bug happening
From: `headers["X-Frame-Options"] == "DENY"`
To: `headers["X-Frame-Options"].downcase == "deny"`

```ruby
 def permit_framing
    headers["X-Frame-Options"] = Lookbook.config.preview_embeds.policy if embedded?
    headers["X-Frame-Options"] = "SAMEORIGIN" if headers["X-Frame-Options"].downcase == "DENY"
  end
```

### Expected behavior
It should set `headers["X-Frame-Options"]` to "SAMEORIGIN"

### Screenshots
![image](https://github.com/ViewComponent/lookbook/assets/40130936/fc84aff0-68c9-47fd-933d-0345e684dd58)

### Version numbers 

Please complete the following information:

* Lookbook: 2.1.1
* ViewComponent: 2.64.0
* Rails:  7.0.4
* Ruby: 3.2.1

**Comment by allmarkedup** [comment]
Hey @louishuyng, many thanks for this. I think it definitely makes sense to normalize the strings to lower or uppercase before comparing them here.

Would you be happy to open a PR with your suggested change?

**Comment by louishuyng** [comment]
@allmarkedup here is the PR for that: https://github.com/ViewComponent/lookbook/pull/554. I guess it just small changes there is enough for fixing this issue

**Comment by allmarkedup** [comment]
@louishuyng merged now :) Many thanks for your time on this, much appreciated.

**Comment by adrienpoly** [comment]
@louishuyng I am getting an error now when I upgraded to 2.20

![CleanShot 2023-11-27 at 10 58 22@2x](https://github.com/ViewComponent/lookbook/assets/7847244/4f8c2d08-7c4c-4612-9332-4f006aaff24d)

**Comment by adrienpoly** [comment]
I will test it, I am pretty sure your proposal should fix it

**Comment by adrienpoly** [comment]
@louishuyng yes it does fix the issue

**Comment by adrienpoly** [comment]
I opened #561 to fix that
