### ISSUE TITLE
Can't draw templates that require instance variables

### ISSUE THREAD

**Issue by vividmuimui** [ViewComponent/lookbook#555]
### Describe the bug

When rendering view templates that require instance variables, the following error occurs
```
ActionView::Template::Error
'nil' is not an ActiveModel-compatible object. It must implement :to_partial_path.
```

### To Reproduce

1. `bin/rails generate scaffold Article title:string body:text`
```erb
# app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <%= link_to "New article", new_article_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="articles" class="min-w-full">
    <%= render @articles %>
  </div>
</div>
```

2.
```rb
# test/components/previews/articles/index_preview.rb
class Articles::IndexPreview < Lookbook::Preview
  def default
    render template: 'articles/index', assigns: { articles: [] }
  end
end
```
3. See error http://localhost:3000/lookbook/inspect/articles/index/default

### Expected behavior

I want the preview to be displayed without error.

### Screenshots

![image](https://github.com/ViewComponent/lookbook/assets/126661836/7fdc4775-8a98-46d0-8320-c7468848c0ce)

### Version numbers 

Please complete the following information:

* Lookbook: 2.1.1
* ViewComponent: -
* Rails: 7.1.2
* Ruby: 3.2.1p31

### Additional context

The following is a sample project that is actually in error.
https://github.com/vividmuimui/LookBookSample/tree/report-issue
https://github.com/vividmuimui/LookBookSample/blob/report-issue/test/components/previews/articles/index_preview.rb

**Comment by allmarkedup** [comment]
Hey @vividmuimui, many thanks for the detailed bug report.

I think I might know why this is not working - I'll take a look now and see if I can get it fixed 👍

**Comment by allmarkedup** [comment]
Hey again @vividmuimui, just to let you know I've just released v2.2.0 that should fix the issue you were seeing. I'm going to go ahead and close this issue now but if you are still having problems with the new version feel free to reopen or let me know. Thanks again for the bug report :)

**Comment by vividmuimui** [comment]
@allmarkedup 
Thanks for the very quick fix!
I was able to confirm that it works fine in v2.2.0.

**Comment by allmarkedup** [comment]
Fantastic, thanks for letting me know!
