### ISSUE TITLE
Documentation request: mention support for Phlex in the README

### ISSUE THREAD

**Issue by brandondrew** [ViewComponent/lookbook#573]
It's fantastic that Lookbook supports Phlex and regular Rails view templates, in addition to components built with ViewComponent. This would (IMHO) be worth mentioning in the README.  Many will otherwise assume based on being developed as part of the  ViewComponent project that it only supports components built with the view_component gem.

**Comment by dhnaranjo** [comment]
Feels like this would be a pretty straightforward thing to submit an unsolicited PR on. Easier for maintainers to approve or critique than to sit down and do the work, nah?

**Comment by Spone** [comment]
Yes, please submit a PR if you can dedicate some time to it, it will help move this forward! Thanks

**Comment by brandondrew** [comment]
> Feels like this would be a pretty straightforward thing to submit an unsolicited PR on. Easier for maintainers to approve or critique than to sit down and do the work, nah?

I think documentation should ideally come from people who know the project. I could mention that Phlex is supported and not much else, but I'm sure a knowledgeable person would think of other points worth mentioning.  

I generally don't do PRs that are not desired, as the work may be wasted. In the case of documentation it might only be a few minutes, so your point would stand *if I really knew enough to be a source of information*.  

If you know enough to have anything useful to say, you could do it.

**Comment by allmarkedup** [comment]
@brandondrew so sorry for the slow reply. PR's are always appreciated but it's no problem for me to add a note in the README about Phlex support. To be honest I thought I had already mentioned it in there but apparently not!

It's definitely a good idea to mention it so I'll add a short note with a link out to the documentation for more info.

Thanks for bringing it to my attention :)

**Comment by allmarkedup** [comment]
I've added a very brief note on compatibility [here](https://github.com/ViewComponent/lookbook#:~:text=It%27s%20compatible%20with%20ViewComponent%2C%20Phlex%2C%20ActionView%20partials%20and%20more.) - hopefully that is enough to get interested people to click through to the main docs site.

I'll go ahead and close this now, thanks for your input everyone.
