### ISSUE TITLE
Update Embed helper to show source code? / Or allowing erb in code blocks to not be rendered?

### ISSUE THREAD

**Issue by afomera** [ViewComponent/lookbook#75]
Hey 👋

Thanks for the continued improvements to Lookbook. 

We've started using Lookbook quite a bit more, and with the new experimental Documentation pages it gives us almost everything I think we need to build out some really slick documentation for our devs on our design system and components.

**One thing I was trying to figure out how to do while experimenting with the new documentation pages was see if it was possible to show the source preview for how we'd have developers render our components from the embeds.** 

The biggest reason for this is we tend to prefer long-form documentation on when we might use each example then having to jump pick through each example we have and then view the source.

![CleanShot 2022-04-06 at 09 33 41@2x](https://user-images.githubusercontent.com/1741179/162013108-628ebbf7-4940-4092-b2dd-8a35e37bf2fa.png)

In this screenshot I was experimenting with seeing if I could add support to make the embed component show the preview source code, but I got stuck and couldn't figure out how to actually show the source code pane 😅

The other thing I tried was using a `code` block to show the erb render tag below the embed preview a developer might use.

<img width="868" alt="CleanShot 2022-04-06 at 09 38 24@2x" src="https://user-images.githubusercontent.com/1741179/162013413-9917a0fc-465a-48d8-87c5-b199897cb548.png">

This was the md.erb file I tried this in:

```
---
id: cards
title: Cards
---

This documentation is still a WIP, so excuse the mess!

Example [Link to the Colors documentation page](<%= page_path :colors %>) to test out the Lookbook UI.

<%= embed Podia::UI::CardComponentPreview, :with_header_and_divider %>

<%= code :erb do %>
  <%= render(Podia::UI::CardComponent.new(header_divider: true)) do |card_component| %>
    <% card_component.header do %>
      <div class="card-title">Custom Title</div>
      <div class="card-subtitle">Custom Subtitle</div>
      <%= render Podia::UI::TabsComponent.new(
        tabs: [
          { id: :tab1, text: "Tab 1", url: "#" },
          { id: :tab2, text: "Tab 2", url: "#" }
        ],
        active: :tab2,
        id: "custom-card-tabs",
        within_card: true
      ) %>
    <% end %>

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero massa, commodo nec orci in, cursus imperdiet sapien. Praesent laoreet diam sollicitudin,
    feugiat sapien ac, scelerisque ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eros eros, mollis sit amet risus id,
    hendrerit ornare massa. Cras sapien nisl, sollicitudin a nisl non, facilisis dapibus eros. Fusce egestas nulla eget convallis bibendum.
    Sed at venenatis nibh, in pulvinar massa. Aenean dignissim ac nulla vel auctor. Praesent gravida quam ut nisi volutpat efficitur
  <% end %>
<% end %>
```

I suppose rendering the ERB tag in the code block happens first before the markdown processing, but I also had this problem on regular .html.erb documentation pages too. Maybe this is expected? I hoped to be able to see my non-rendered ERB so a developer could copy the erb they might use for that preview to use in the app.

Is this something Lookbook might want to support?

**Comment by allmarkedup** [comment]
Hey @afomera, good to hear from you and really glad you are liking the new features :-)

This is absolutely something I intend to add - I wanted to keep the scope of the pages feature as small as possible in order to get it out into the wild. But adding the ability to (optionally) display source code (and possibly even edit params etc) in the component embed is something I want to add very soon. And also some way to display the source code of a preview independently from the embed too, I think.

Regarding the issue with the source code rendering - yes you are correct, unfortunately the ERB is rendered before the markdown parsing happens. However as a temporary solution until a proper source code embed is available, you should be able to manually escape the `<` and `>` characters as HTML entities (`&lt;` and `&gt;` respectively) to prevent the ERB being run, and they should be correctly converted back when the code highlighting happens.

I realise that is a bit of a pain to do manually but I hope to get to the source code embed as soon as I can :-)

**Comment by allmarkedup** [comment]
Hey @afomera, I realise you opened this issue a long time ago now but I've finally released something along the lines of your feature request as part of the first [v2.0 beta release](https://github.com/ViewComponent/lookbook/discussions/310) so I thought I'd just let you know!

It's now possible to show any of the panels that are available in the 'main' preview in the embedded preview instances too. [The docs have been updated](https://v2.lookbook.build/guide/pages/embedding) with some more examples and info.

Actually, it's now also possible to use the same embeds outside of your Lookbook instance too for those that want to include them in other places ([there are [some examples of what that looks like here](http://v2-demo.lookbook.build/embeds) in case you are interested!).

I'll go ahead and close this issue down now but thanks again for your original suggestion and if this is still relevant to you and you have any questions please just let me know - I'll try to get back to you a little quicker next time 😄

**Comment by afomera** [comment]
This is great thank you @allmarkedup will try to poke the folks running our ViewComponent project this is possible now.
